spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/qna
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug